config/routes.rb
Rails.application.routes.draw do
  resources :contact_us_requests
  resources :departures
  get "/contact-us" => "contact_us#new"

  resources :contact_us
  root "pages#home"
  get "/index" => "pages#home"
  get '/why-travel-with-us' => "pages#why", as: "why"
  get '/privacy-policy' => "pages#privacy", as: "privacy"

  resources :statements
  resources :lodgings
  resources :itinerary_days
  resources :trips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/itinerary_day.rb
class ItineraryDay < ApplicationRecord
  belongs_to :trip
end

app/controllers/itinerary_days_controller.rb
class ItineraryDaysController < ApplicationController
  before_action :set_itinerary_day, only: %i[ show edit update destroy ]

  # GET /itinerary_days or /itinerary_days.json
  def index
    @itinerary_days = ItineraryDay.all
  end

  # GET /itinerary_days/1 or /itinerary_days/1.json
  def show
  end

  # GET /itinerary_days/new
  def new
    @itinerary_day = ItineraryDay.new
  end

  # GET /itinerary_days/1/edit
  def edit
  end

  # POST /itinerary_days or /itinerary_days.json
  def create
    @itinerary_day = ItineraryDay.new(itinerary_day_params)

    respond_to do |format|
      if @itinerary_day.save
        format.html { redirect_to itinerary_day_url(@itinerary_day), notice: "Itinerary day was successfully created." }
        format.json { render :show, status: :created, location: @itinerary_day }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @itinerary_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /itinerary_days/1 or /itinerary_days/1.json
  def update
    respond_to do |format|
      if @itinerary_day.update(itinerary_day_params)
        format.html { redirect_to itinerary_day_url(@itinerary_day), notice: "Itinerary day was successfully updated." }
        format.json { render :show, status: :ok, location: @itinerary_day }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @itinerary_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itinerary_days/1 or /itinerary_days/1.json
  def destroy
    @itinerary_day.destroy

    respond_to do |format|
      format.html { redirect_to itinerary_days_url, notice: "Itinerary day was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itinerary_day
      @itinerary_day = ItineraryDay.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def itinerary_day_params
      params.require(:itinerary_day).permit(:trip_id, :days, :header, :day_text, :position)
    end
end

app/helpers/itinerary_days_helper.rb
module ItineraryDaysHelper
end

app/views/itinerary_days/_form.html.erb
<%= form_with(model: itinerary_day) do |form| %>
  <% if itinerary_day.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(itinerary_day.errors.count, "error") %> prohibited this itinerary_day from being saved:</h2>

      <ul>
        <% itinerary_day.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :trip_id, style: "display: block" %>
    <%= form.text_field :trip_id %>
  </div>

  <div>
    <%= form.label :days, style: "display: block" %>
    <%= form.text_field :days %>
  </div>

  <div>
    <%= form.label :header, style: "display: block" %>
    <%= form.text_field :header %>
  </div>

  <div>
    <%= form.label :day_text, style: "display: block" %>
    <%= form.text_area :day_text %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/itinerary_days/_itinerary_day.html.erb
<div id="<%= dom_id itinerary_day %>">
  <p>
    <strong>Trip:</strong>
    <%= itinerary_day.trip_id %>
  </p>

  <p>
    <strong>Days:</strong>
    <%= itinerary_day.days %>
  </p>

  <p>
    <strong>Header:</strong>
    <%= itinerary_day.header %>
  </p>

  <p>
    <strong>Day text:</strong>
    <%= itinerary_day.day_text %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= itinerary_day.position %>
  </p>

</div>

app/views/itinerary_days/edit.html.erb
<h1>Editing itinerary day</h1>

<%= render "form", itinerary_day: @itinerary_day %>

<br>

<div>
  <%= link_to "Show this itinerary day", @itinerary_day %> |
  <%= link_to "Back to itinerary days", itinerary_days_path %>
</div>

app/views/itinerary_days/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Itinerary days</h1>

<div id="itinerary_days">
  <% @itinerary_days.each do |itinerary_day| %>
    <%= render itinerary_day %>
    <p>
      <%= link_to "Show this itinerary day", itinerary_day %>
    </p>
  <% end %>
</div>

<%= link_to "New itinerary day", new_itinerary_day_path %>

app/views/itinerary_days/new.html.erb
<h1>New itinerary day</h1>

<%= render "form", itinerary_day: @itinerary_day %>

<br>

<div>
  <%= link_to "Back to itinerary days", itinerary_days_path %>
</div>

app/views/itinerary_days/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @itinerary_day %>

<div>
  <%= link_to "Edit this itinerary day", edit_itinerary_day_path(@itinerary_day) %> |
  <%= link_to "Back to itinerary days", itinerary_days_path %>

  <%= button_to "Destroy this itinerary day", @itinerary_day, method: :delete %>
</div>