config/routes.rb
Rails.application.routes.draw do
  resources :contact_us_requests
  resources :departures
  get "/contact-us" => "contact_us#new"

  resources :contact_us
  root "pages#home"
  get "/index" => "pages#home"
  get '/why-travel-with-us' => "pages#why", as: "why"
  get '/privacy-policy' => "pages#privacy", as: "privacy"

  resources :statements
  resources :lodgings
  resources :itinerary_days
  resources :trips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/departure.rb
class Departure < ApplicationRecord
  default_scope { order('departure_date') }
  belongs_to :trip
end

app/controllers/departures_controller.rb
class DeparturesController < ApplicationController
  before_action :set_departure, only: %i[ show edit update destroy ]

  # GET /departures or /departures.json
  def index
    @departures = Departure.all
  end

  # GET /departures/1 or /departures/1.json
  def show
  end

  # GET /departures/new
  def new
    @departure = Departure.new
  end

  # GET /departures/1/edit
  def edit
  end

  # POST /departures or /departures.json
  def create
    @departure = Departure.new(departure_params)

    respond_to do |format|
      if @departure.save
        format.html { redirect_to departure_url(@departure), notice: "Departure was successfully created." }
        format.json { render :show, status: :created, location: @departure }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @departure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departures/1 or /departures/1.json
  def update
    respond_to do |format|
      if @departure.update(departure_params)
        format.html { redirect_to departure_url(@departure), notice: "Departure was successfully updated." }
        format.json { render :show, status: :ok, location: @departure }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @departure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departures/1 or /departures/1.json
  def destroy
    @departure.destroy

    respond_to do |format|
      format.html { redirect_to departures_url, notice: "Departure was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departure
      @departure = Departure.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def departure_params
      params.require(:departure).permit(:departure_date, :return_date, :price, :difficulty_level)
    end
end

app/helpers/departures_helper.rb
module DeparturesHelper
end

app/views/departures/_departure.html.erb
<div id="<%= dom_id departure %>">
  <p>
    <strong>Trip:</strong>
    <%= departure.trip_id %>
  </p>

  <p>
    <strong>Departure date:</strong>
    <%= departure.departure_date %>
  </p>

  <p>
    <strong>Return date:</strong>
    <%= departure.return_date %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= departure.price %>
  </p>

  <p>
    <strong>Difficulty level:</strong>
    <%= departure.difficulty_level %>
  </p>

</div>

app/views/departures/_form.html.erb
<%= form_with(model: departure) do |form| %>
  <% if departure.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(departure.errors.count, "error") %> prohibited this departure from being saved:</h2>

      <ul>
        <% departure.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :trip_id, style: "display: block" %>
    <%= form.text_field :trip_id %>
  </div>

  <div>
    <%= form.label :departure_date, style: "display: block" %>
    <%= form.date_field :departure_date %>
  </div>

  <div>
    <%= form.label :return_date, style: "display: block" %>
    <%= form.date_field :return_date %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price %>
  </div>

  <div>
    <%= form.label :difficulty_level, style: "display: block" %>
    <%= form.text_field :difficulty_level %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/departures/edit.html.erb
<h1>Editing departure</h1>

<%= render "form", departure: @departure %>

<br>

<div>
  <%= link_to "Show this departure", @departure %> |
  <%= link_to "Back to departures", departures_path %>
</div>

app/views/departures/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Departures</h1>

<div id="departures">
  <% @departures.each do |departure| %>
    <%= render departure %>
    <p>
      <%= link_to "Show this departure", departure %>
    </p>
  <% end %>
</div>

<%= link_to "New departure", new_departure_path %>

app/views/departures/new.html.erb
<h1>New departure</h1>

<%= render "form", departure: @departure %>

<br>

<div>
  <%= link_to "Back to departures", departures_path %>
</div>

app/views/departures/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @departure %>

<div>
  <%= link_to "Edit this departure", edit_departure_path(@departure) %> |
  <%= link_to "Back to departures", departures_path %>

  <%= button_to "Destroy this departure", @departure, method: :delete %>
</div>