config/routes.rb
Rails.application.routes.draw do
  resources :contact_us_requests
  resources :departures
  get "/contact-us" => "contact_us#new"

  resources :contact_us
  root "pages#home"
  get "/index" => "pages#home"
  get '/why-travel-with-us' => "pages#why", as: "why"
  get '/privacy-policy' => "pages#privacy", as: "privacy"

  resources :statements
  resources :lodgings
  resources :itinerary_days
  resources :trips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/contact_us_request.rb
class ContactUsRequest < ApplicationRecord
end

app/controllers/contact_us_requests_controller.rb
class ContactUsRequestsController < ApplicationController
  before_action :set_contact_us_request, only: %i[ show edit update destroy ]

  # GET /contact_us_requests or /contact_us_requests.json
  def index
    @contact_us_requests = ContactUsRequest.all
  end

  # GET /contact_us_requests/1 or /contact_us_requests/1.json
  def show
  end

  # GET /contact_us_requests/new
  def new
    @contact_us_request = ContactUsRequest.new
  end

  # GET /contact_us_requests/1/edit
  def edit
  end

  # POST /contact_us_requests or /contact_us_requests.json
  def create
    @contact_us_request = ContactUsRequest.new(contact_us_request_params)

    respond_to do |format|
      if @contact_us_request.save
        format.html { redirect_to contact_us_request_url(@contact_us_request), notice: "Contact us request was successfully created." }
        format.json { render :show, status: :created, location: @contact_us_request }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact_us_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_us_requests/1 or /contact_us_requests/1.json
  def update
    respond_to do |format|
      if @contact_us_request.update(contact_us_request_params)
        format.html { redirect_to contact_us_request_url(@contact_us_request), notice: "Contact us request was successfully updated." }
        format.json { render :show, status: :ok, location: @contact_us_request }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact_us_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_us_requests/1 or /contact_us_requests/1.json
  def destroy
    @contact_us_request.destroy

    respond_to do |format|
      format.html { redirect_to contact_us_requests_url, notice: "Contact us request was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_us_request
      @contact_us_request = ContactUsRequest.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def contact_us_request_params
      params.require(:contact_us_request).permit(:name, :regarding, :phone_number, :email_address, :message)
    end
end

app/helpers/contact_us_requests_helper.rb
module ContactUsRequestsHelper
end

app/views/contact_us_requests/_contact_us_request.html.erb
<div id="<%= dom_id contact_us_request %>">
  <p>
    <strong>Name:</strong>
    <%= contact_us_request.name %>
  </p>

  <p>
    <strong>Regarding:</strong>
    <%= contact_us_request.regarding %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= contact_us_request.phone_number %>
  </p>

  <p>
    <strong>Email address:</strong>
    <%= contact_us_request.email_address %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= contact_us_request.message %>
  </p>

</div>

app/views/contact_us_requests/_form.html.erb
<%= form_with(model: contact_us_request) do |form| %>
  <% if contact_us_request.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact_us_request.errors.count, "error") %> prohibited this contact_us_request from being saved:</h2>

      <ul>
        <% contact_us_request.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :regarding, style: "display: block" %>
    <%= form.text_field :regarding %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number %>
  </div>

  <div>
    <%= form.label :email_address, style: "display: block" %>
    <%= form.text_field :email_address %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.text_area :message %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/contact_us_requests/edit.html.erb
<h1>Editing contact us request</h1>

<%= render "form", contact_us_request: @contact_us_request %>

<br>

<div>
  <%= link_to "Show this contact us request", @contact_us_request %> |
  <%= link_to "Back to contact us requests", contact_us_requests_path %>
</div>

app/views/contact_us_requests/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Contact us requests</h1>

<div id="contact_us_requests">
  <% @contact_us_requests.each do |contact_us_request| %>
    <%= render contact_us_request %>
    <p>
      <%= link_to "Show this contact us request", contact_us_request %>
    </p>
  <% end %>
</div>

<%= link_to "New contact us request", new_contact_us_request_path %>

app/views/contact_us_requests/new.html.erb
<h1>New contact us request</h1>

<%= render "form", contact_us_request: @contact_us_request %>

<br>

<div>
  <%= link_to "Back to contact us requests", contact_us_requests_path %>
</div>

app/views/contact_us_requests/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact_us_request %>

<div>
  <%= link_to "Edit this contact us request", edit_contact_us_request_path(@contact_us_request) %> |
  <%= link_to "Back to contact us requests", contact_us_requests_path %>

  <%= button_to "Destroy this contact us request", @contact_us_request, method: :delete %>
</div>