config/routes.rb
Rails.application.routes.draw do
  resources :contact_us_requests
  resources :departures
  get "/contact-us" => "contact_us#new"

  resources :contact_us
  root "pages#home"
  get "/index" => "pages#home"
  get '/why-travel-with-us' => "pages#why", as: "why"
  get '/privacy-policy' => "pages#privacy", as: "privacy"

  resources :statements
  resources :lodgings
  resources :itinerary_days
  resources :trips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/lodging.rb
class Lodging < ApplicationRecord
  belongs_to :trip
end

app/controllers/lodgings_controller.rb
class LodgingsController < ApplicationController
  before_action :set_lodging, only: %i[ show edit update destroy ]

  # GET /lodgings or /lodgings.json
  def index
    @lodgings = Lodging.all
  end

  # GET /lodgings/1 or /lodgings/1.json
  def show
  end

  # GET /lodgings/new
  def new
    @lodging = Lodging.new
  end

  # GET /lodgings/1/edit
  def edit
  end

  # POST /lodgings or /lodgings.json
  def create
    @lodging = Lodging.new(lodging_params)

    respond_to do |format|
      if @lodging.save
        format.html { redirect_to lodging_url(@lodging), notice: "Lodging was successfully created." }
        format.json { render :show, status: :created, location: @lodging }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @lodging.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lodgings/1 or /lodgings/1.json
  def update
    respond_to do |format|
      if @lodging.update(lodging_params)
        format.html { redirect_to lodging_url(@lodging), notice: "Lodging was successfully updated." }
        format.json { render :show, status: :ok, location: @lodging }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @lodging.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lodgings/1 or /lodgings/1.json
  def destroy
    @lodging.destroy

    respond_to do |format|
      format.html { redirect_to lodgings_url, notice: "Lodging was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lodging
      @lodging = Lodging.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def lodging_params
      params.require(:lodging).permit(:trip_id, :position, :name, :location, :level, :number_of_nights, :description, :photo, :photo_alt)
    end
end

app/helpers/lodgings_helper.rb
module LodgingsHelper
end

app/views/lodgings/_form.html.erb
<%= form_with(model: lodging) do |form| %>
  <% if lodging.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(lodging.errors.count, "error") %> prohibited this lodging from being saved:</h2>

      <ul>
        <% lodging.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :trip_id, style: "display: block" %>
    <%= form.text_field :trip_id %>
  </div>

  <div>
    <%= form.label :position, style: "display: block" %>
    <%= form.number_field :position %>
  </div>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_field :location %>
  </div>

  <div>
    <%= form.label :level, style: "display: block" %>
    <%= form.text_field :level %>
  </div>

  <div>
    <%= form.label :number_of_nights, style: "display: block" %>
    <%= form.text_field :number_of_nights %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :photo, style: "display: block" %>
    <%= form.text_field :photo %>
  </div>

  <div>
    <%= form.label :photo_alt, style: "display: block" %>
    <%= form.text_field :photo_alt %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/lodgings/_lodging.html.erb
<div id="<%= dom_id lodging %>">
  <p>
    <strong>Trip:</strong>
    <%= lodging.trip_id %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= lodging.position %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= lodging.name %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= lodging.location %>
  </p>

  <p>
    <strong>Level:</strong>
    <%= lodging.level %>
  </p>

  <p>
    <strong>Number of nights:</strong>
    <%= lodging.number_of_nights %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= lodging.description %>
  </p>

  <p>
    <strong>Photo:</strong>
    <%= lodging.photo %>
  </p>

  <p>
    <strong>Photo alt:</strong>
    <%= lodging.photo_alt %>
  </p>

</div>

app/views/lodgings/edit.html.erb
<h1>Editing lodging</h1>

<%= render "form", lodging: @lodging %>

<br>

<div>
  <%= link_to "Show this lodging", @lodging %> |
  <%= link_to "Back to lodgings", lodgings_path %>
</div>

app/views/lodgings/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Lodgings</h1>

<div id="lodgings">
  <% @lodgings.each do |lodging| %>
    <%= render lodging %>
    <p>
      <%= link_to "Show this lodging", lodging %>
    </p>
  <% end %>
</div>

<%= link_to "New lodging", new_lodging_path %>

app/views/lodgings/new.html.erb
<h1>New lodging</h1>

<%= render "form", lodging: @lodging %>

<br>

<div>
  <%= link_to "Back to lodgings", lodgings_path %>
</div>

app/views/lodgings/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @lodging %>

<div>
  <%= link_to "Edit this lodging", edit_lodging_path(@lodging) %> |
  <%= link_to "Back to lodgings", lodgings_path %>

  <%= button_to "Destroy this lodging", @lodging, method: :delete %>
</div>